### PR TITLE
Updated 'Enable' column and translated into German

### PR DESCRIPTION
**Pull request by pikim**

### CODE REVIEW

**Comment by ryecoaaron** [comment]
I appreciate the help but your translations will be over-written when I sync from transifex.  The file is also "cleaned up" automatically during the sync.  If you sign-up at transifex, I can accept your request to be a translator.

**Comment by pikim** [comment]
I've signed up there with the same username and already joined the team and translated the missing strings. I don't know whether I did it the right way.

But one of the pull requests remains anyway.

**Comment by ryecoaaron** [comment]
translations updated from transifex and package updated in repo

**Comment by pikim** [comment]
Thanks a lot. Unfortunately I just translated the strings that remained in the file in my commit from above. Now I also translated the others.

But it seems like they're taken from anywhere else, so it shouldn't be a big problem. Sorry for the inconvenience.

**Pull request merged**
